### ISSUE TITLE
Thanks for updating this Tony but it can be better if you include how to upload the model to aws.

### ISSUE THREAD

**Issue by arrickx** [TonyMarkham/LocalDeepRacerUbuntuInstallation#3]
I believe most student here are able to re-create this environment. But it's very few student can understand how to upload the model online. If possible, please help us to unlock this challenge.
Best Regards

**Comment by TonyMarkham** [comment]
I use this guide to upload my models.

https://github.com/crr0004/deepracer/wiki/Uploading-to-Leaderboard
